version: "1.0"
name: media-stack
services:
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment: 
      - SURFSHARK_USER=exzSesh8r2z4GHBEdVW3VU7W
      - SURFSHARK_PASSWORD=rXXzzUAQtdTzk52qsvWgza7Q
      - SURFSHARK_COUNTRY=
      - SURFSHARK_CITY=
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=10.0.1.0/24
    networks:
      - mynetwork    
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
      - 5080:5080
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    dns:
      - 1.1.1.1
    
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on: 
      - surfshark    
    network_mode: service:surfshark      
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbt-config:/config
      - torrent-downloads:/downloads
#    ports:
#      - 5080:5080
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    depends_on: 
      - surfshark        
    network_mode: service:surfshark      
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=admin
      - PASS=nimdatx
#    ports:
#      - 9091:9091
#      - 51413:51413
#      - 51413:51413/udp
    volumes:
      - tx-config:/config
      - torrent-downloads:/downloads
      - tx-watch:/watch
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on: 
      - transmission
      - qbittorrent
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:v4-4.0.0.141-ls6
    depends_on: 
      - transmission
      - qbittorrent
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on: 
      - transmission
      - qbittorrent
    networks:
      - mynetwork      
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - bazarr-config:/config
      - torrent-downloads:/data      
    ports:
      - 6767:6767
    restart: unless-stopped    

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    depends_on: 
      - transmission
      - qbittorrent    
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  qbt-config:
  bazarr-config:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true
